{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servers-dashboard.serviceAccountName" . }}
  labels:
    {{- include "servers-dashboard.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "servers-dashboard.fullname" . }}-role
  labels:
    {{- include "servers-dashboard.labels" . | nindent 4 }}
rules:
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "servers-dashboard.fullname" . }}-rolebinding
  labels:
    {{- include "servers-dashboard.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "servers-dashboard.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "servers-dashboard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
